SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM (
         SELECT *,
                DENSE_RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) AS rk
         FROM FOOD_PRODUCT
     ) t
WHERE rk = 1 AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY PRICE DESC